import type {
  JORFSearchItem,
  JORFSearchOrganisation,
} from "../JORFSearch.utils.ts";

/** A person's publication history, shaped for rendering. */
export interface PersonProfile {
  prenom: string;
  nom: string;
  displayName: string;
  sexe?: "F" | "M";
  wikidataId?: string;
  records: JORFSearchItem[];
  firstDate?: string;
  lastDate?: string;
  organisations: JORFSearchOrganisation[];
  latestGrade?: string;
  latestOrganisation?: string;
}

const FRENCH_MONTHS = [
  "janvier",
  "février",
  "mars",
  "avril",
  "mai",
  "juin",
  "juillet",
  "août",
  "septembre",
  "octobre",
  "novembre",
  "décembre",
];

/** Format an ISO date as a French long date. */
export function formatFrenchDate(iso: string): string {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
  if (match === null) return iso;
  const year = match[1];
  const month = FRENCH_MONTHS[Number(match[2]) - 1] ?? "";
  const day = Number(match[3]);
  return `${day === 1 ? "1er" : String(day)} ${month} ${year}`;
}

/** Order-of-business label for a record, in French. */
export function typeOrdreLabel(typeOrdre: string | undefined): string {
  switch (typeOrdre) {
    case "nomination":
      return "Nomination";
    case "reconduction":
      return "Reconduction";
    case "promotion":
      return "Promotion";
    case "cessation de fonction":
    case "cessation de fonctions":
      return "Cessation de fonctions";
    case "affectation":
      return "Affectation";
    case "délégation de signature":
      return "Délégation de signature";
    case "habilitation":
      return "Habilitation";
    case "admission":
      return "Admission";
    case "élection":
      return "Élection";
    case "décoration":
      return "Décoration";
    case undefined:
      return "Publication";
    default:
      return typeOrdre.charAt(0).toUpperCase() + typeOrdre.slice(1);
  }
}

function byDateDescending(a: JORFSearchItem, b: JORFSearchItem): number {
  return (b.source_date ?? "").localeCompare(a.source_date ?? "");
}

/** Collapse a person's records into the shape the page renders. */
export function buildProfile(records: JORFSearchItem[]): PersonProfile | null {
  if (records.length === 0) return null;

  const sorted = [...records].sort(byDateDescending);
  const first = sorted[0];
  const dates = sorted
    .map((r) => r.source_date)
    .filter((d): d is string => d !== undefined)
    .sort();

  const organisations = new Map<string, JORFSearchOrganisation>();
  for (const record of sorted) {
    for (const organisation of record.organisations ?? []) {
      if (!organisations.has(organisation.nom)) {
        organisations.set(organisation.nom, organisation);
      }
    }
  }

  // The person-level Wikidata id, never the one attached to an organisation.
  const wikidataId = sorted.find(
    (r) => typeof r.wikidata_id === "string" && r.wikidata_id.length > 0,
  )?.wikidata_id;

  return {
    prenom: first.prenom,
    nom: first.nom,
    displayName: `${first.prenom} ${first.nom}`,
    sexe: first.sexe,
    wikidataId,
    records: sorted,
    firstDate: dates[0],
    lastDate: dates[dates.length - 1],
    organisations: [...organisations.values()],
    latestGrade: sorted.find((r) => r.grade !== undefined)?.grade,
    latestOrganisation: sorted.find((r) => (r.organisations?.length ?? 0) > 0)
      ?.organisations?.[0]?.nom,
  };
}

/**
 * A plain-French summary built from the record fields.
 *
 * Generated by template rather than by a model, so the same data always
 * produces the same sentence and nothing is asserted that the records do not
 * contain. Degrades to a single valid sentence when only a name and a date are
 * known.
 */
export function buildSummary(profile: PersonProfile): string {
  const count = profile.records.length;
  const plural = count > 1 ? "s" : "";
  const sentences: string[] = [];

  const range =
    profile.firstDate !== undefined &&
    profile.lastDate !== undefined &&
    profile.firstDate !== profile.lastDate
      ? ` entre le ${formatFrenchDate(profile.firstDate)} et le ${formatFrenchDate(profile.lastDate)}`
      : profile.lastDate !== undefined
        ? ` le ${formatFrenchDate(profile.lastDate)}`
        : "";

  sentences.push(
    `${profile.displayName} fait l'objet de ${String(count)} publication${plural} au Journal officiel de la République française${range}.`,
  );

  const latest = profile.records[0];
  if (latest.source_date !== undefined) {
    const what = typeOrdreLabel(latest.type_ordre).toLowerCase();
    const grade =
      latest.grade !== undefined ? ` en qualité de ${latest.grade}` : "";
    const org =
      profile.latestOrganisation !== undefined
        ? ` au sein de : ${profile.latestOrganisation}`
        : "";
    if (grade !== "" || org !== "") {
      sentences.push(
        `La publication la plus récente est une ${what}${grade}${org}, parue le ${formatFrenchDate(latest.source_date)}.`,
      );
    }
  }

  const orgCount = profile.organisations.length;
  if (orgCount > 1) {
    sentences.push(
      `${String(orgCount)} organisations sont mentionnées dans ces publications.`,
    );
  }

  return sentences.join(" ");
}

/** Légifrance URL for a JORFTEXT identifier. */
export function legifranceUrl(sourceId: string): string {
  return `https://www.legifrance.gouv.fr/jorf/id/${encodeURIComponent(sourceId)}`;
}

/**
 * Whether a record's name fields actually look like a person's name.
 *
 * JORFSearch carries a small number of records whose `prenom` is a session
 * year and whose `nom` is a whole report title, for example
 * `prenom: "2024-2025", nom: "Agnès Canayer sur la proposition de loi n° 636"`.
 * Publishing those as person pages would create URLs that are neither useful
 * nor correct, so they are filtered out rather than rendered.
 *
 * This is a plausibility check, not a validation one: it decides what deserves
 * a page, not what is safe to process.
 */
export function isPlausiblePersonName(
  prenom: string | undefined,
  nom: string | undefined,
): boolean {
  if (prenom === undefined || nom === undefined) return false;
  if (prenom.trim().length === 0 || nom.trim().length === 0) return false;
  if (prenom.length > 40 || nom.length > 40) return false;
  if (/\d/.test(prenom) || /\d/.test(nom)) return false;
  return `${prenom} ${nom}`.trim().split(/\s+/).length <= 6;
}
